# Generated by Django 4.0.4 on 2022-04-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hours', models.IntegerField(blank=True, default=0)),
                ('completion_status', models.CharField(choices=[('I', 'Incomplete'), ('P', 'Playing'), ('C', 'Complete')], max_length=1)),
            ],
        ),
    ]
