# Generated by Django 4.0.4 on 2022-04-19 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinfo',
            name='date_added',
        ),
    ]
